version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run:
         name: Check Node Version
         command: "node --version"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Refresh APT Repositories
          command: sudo apt-get update -y  
      - run:
          name: Install Dependencies
          command: | 
            npm install
            sudo apt-get update -y  
            sudo apt-get install -y dpkg fakeroot rpm

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Make Using Electron Forge
          command: npm run make

      - store_artifacts:
          path: out/make